// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'PUT YOUR KEY HERE',
    appId: '1:951131963362:web:57473d5ee9829b471dc3bb',
    messagingSenderId: '951131963362',
    projectId: 'appointer-project',
    authDomain: 'appointer-project.firebaseapp.com',
    storageBucket: 'appointer-project.appspot.com',
    measurementId: 'G-SQVZX0BTM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'PUT YOUR KEY HERE',
    appId: '1:951131963362:android:ca06eb1de4b35ce21dc3bb',
    messagingSenderId: '951131963362',
    projectId: 'appointer-project',
    storageBucket: 'appointer-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_iEv6lsL3cndI_V0ER4TrndQjMpAJBl0',
    appId: '1:951131963362:ios:56b858d9ae5f71441dc3bb',
    messagingSenderId: '951131963362',
    projectId: 'appointer-project',
    storageBucket: 'appointer-project.appspot.com',
    iosBundleId: 'com.appointerbyasps.appoiter',
  );
}
